name: build
run-name: Build Corne 3x6 nice!view nice!nano (${{ github.ref_name }})
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - config/**
      - boards/**
      - build.yaml

jobs:
  build:
    # uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
