name: 'Build Corne 3x6 nice!view nice!nano Firmware'
# name: Test Corne 3x6 nice!view nice!nano
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
